### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by akiramenowaruiotoko** [akiramenowaruiotoko/protospace-31106#1]
ProtoSpaceのURL
https://github.com/akiramenowaruiotoko/protospace-31106

本番環境(Heroku)のURL
 https://protospace-31106.herokuapp.com/

**Comment by kouhei-masuda** [comment]
澤口さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by akiramenowaruiotoko** [comment]
ご確認とLGTMありがとうございました。
